### ISSUE TITLE
Improve structure

### ISSUE THREAD

**Issue by skogsbrus** [skogsbrus/os#14]
Got help from @phaer and jakehamilton.

References:
- https://github.com/jakehamilton/config/tree/main/machines/x86_64-linux
- https://github.com/jakehamilton/config/blob/main/modules/virtualisation/kvm.nix
- https://nixos.org/manual/nixos/stable/index.html#sec-option-declarations

Misc
- Namespace?

Improvements:

* You can pass extra arguments to your home-manager config by adding it to home-manager.extraSpecialArgs. E.g. i use home-manager.extraSpecialArgs.osConfig = config; in my nixos configuration, so i get osConfig in my home manager modules. so i.e. osConfig.networking.hostName works.

**Comment by skogsbrus** [comment]
Fixed for `sys` in https://github.com/skogsbrus/os/pull/15

**Comment by phaer** [comment]
Just FYI: @-mentioning people on Github subscribes them to issues by default. :) I'll unsubscribe myself here, as this seems to be your personal project :+1:

**Comment by skogsbrus** [comment]
Oh lol sorry! :bow: Didn't consider you'd have the same nick on github

**Comment by phaer** [comment]
No worries, just thought that the detailed effects of mentions can be confusing. Especially with the nixos ecosystem, where mentioning nixpkgs-maintainers pings 500+ people *and* subscribes them to all following posts in the thread automatically with no way to remove everyone at once. https://github.com/NixOS/nixpkgs/pull/179598#issuecomment-1173951519 

so no worries ;)

**Comment by skogsbrus** [comment]
Oh yeah, I do remember seeing this one https://github.com/EpicGames/Signup/pull/24. Ouch! :laughing: 

Complete with https://github.com/skogsbrus/os/pull/16
